version: '3'
services:

  article:
      build: ./article
      image: fuoni/article:1.0.0
      container_name: article
      environment:
        - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/article

  news:
      build: ./news
      image: fuoni/news:1.0.0
      container_name: news
      environment:
        - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/news

  portfolio:
      build: ./portfolio
      image: fuoni/portfolio:1.0.0
      container_name: portfolio
      environment:
        - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/portfolio

  stock:
      build: ./stock
      image: fuoni/stock:1.0.0
      container_name: stock
      environment:
        - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/stock

  user:
      build: ./user
      image: fuoni/user:1.0.0
      container_name: user
      environment:
        - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/user

